# Generated by Django 6.1 on 2026-08-31 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        ('students', '0002_alter_academiccommittee_fecha_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CONGRESO_NACIONAL', 'Congreso Nacional'), ('CONGRESO_INTERNACIONAL', 'Congreso Internacional'), ('COLOQUIO', 'Coloquio / Simposio de Posgrado')], default='CONGRESO_INTERNACIONAL', max_length=30, verbose_name='Tipo de Evento Académico')),
                ('nombre_evento', models.CharField(max_length=255, verbose_name='Nombre del Evento / Conferencia')),
                ('titulo_ponencia', models.CharField(max_length=255, verbose_name='Título de la Ponencia o Presentación')),
                ('fecha_presentacion', models.DateField(verbose_name='Fecha de Presentación')),
                ('sede_lugar', models.CharField(max_length=255, verbose_name='Sede / Ciudad / País')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], default='PRESENCIAL', max_length=20, verbose_name='Modalidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_events', to='evidence.evidence')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_events', to='students.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_events', to='students.student')),
            ],
            options={
                'verbose_name': 'Evento Académico y Congreso',
                'verbose_name_plural': 'Eventos Académicos y Congresos',
                'ordering': ['-fecha_presentacion'],
            },
        ),
        migrations.CreateModel(
            name='OtherProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('SOFTWARE', 'Desarrollo de Software / Librería'), ('PROTOTIPO', 'Prototipo Tecnológico'), ('PATENTE', 'Registro de Patente o Modelo de Utilidad')], default='SOFTWARE', max_length=30, verbose_name='Tipo de Producto')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripción Técnica y Resultados')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='other_products', to='evidence.evidence')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_products', to='students.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_products', to='students.student')),
            ],
            options={
                'verbose_name': 'Otro Producto de Investigación',
                'verbose_name_plural': 'Otros Productos de Investigación',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título de la Publicación')),
                ('autores_texto', models.CharField(max_length=255, verbose_name='Autores (Formato APA)')),
                ('tipo', models.CharField(choices=[('ARTICULO_JCR', 'Artículo Indexado JCR / Scopus'), ('ARTICULO_CONACYT', 'Artículo Revista Padrón Conahcyt'), ('CAPITULO_LIBRO', 'Capítulo de Libro Arbitrado')], default='ARTICULO_JCR', max_length=30, verbose_name='Tipo de Publicación')),
                ('revista_editorial', models.CharField(max_length=255, verbose_name='Revista o Editorial')),
                ('estado', models.CharField(choices=[('PREPARACION', 'En Preparación'), ('ENVIADO', 'Enviado a Editorial'), ('EN_REVISION', 'En Revisión por Pares'), ('ACEPTADO', 'Aceptado para Publicación'), ('PUBLICADO', 'Publicado Oficialmente')], default='PREPARACION', max_length=20, verbose_name='Estado del Artículo')),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación / Envío')),
                ('doi_url', models.URLField(blank=True, default='', verbose_name='DOI o Enlace Web')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='evidence.evidence')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='students.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='students.student')),
            ],
            options={
                'verbose_name': 'Publicación Científica',
                'verbose_name_plural': 'Publicaciones Científicas',
                'ordering': ['-fecha_publicacion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_receptora', models.CharField(max_length=255, verbose_name='Institución o Universidad Receptora')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('responsable_estancia', models.CharField(max_length=255, verbose_name='Investigador Anfitrión / Responsable')),
                ('objetivos', models.TextField(verbose_name='Objetivos y Resultados de la Estancia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_stays', to='evidence.evidence')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_stays', to='students.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_stays', to='students.student')),
            ],
            options={
                'verbose_name': 'Estancia de Investigación Doctoral',
                'verbose_name_plural': 'Estancias de Investigación Doctoral',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
