# Generated by Django 6.1 on 2026-08-31 21:18

import apps.thesis.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_academiccommittee_fecha_asignacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThesisProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_avance', models.PositiveSmallIntegerField(help_text='Porcentaje de 0 a 100 del avance longitudinal de investigación.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje Global de Avance de Tesis')),
                ('componentes_json', models.JSONField(default=apps.thesis.models.default_thesis_components, help_text='JSON con el estado de avance por áreas temáticas.', verbose_name='Desglose de Componentes de Tesis')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones Académicas del Avance')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha del Registro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_thesis_progress', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_progress_records', to='students.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis_progress_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Avance de Tesis Doctoral',
                'verbose_name_plural': 'Avances de Tesis Doctoral',
                'ordering': ['-fecha_registro', '-created_at'],
            },
        ),
    ]
