# Generated by Django 6.1 on 2026-08-31 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_academiccommittee_fecha_asignacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sesion', models.DateField(verbose_name='Fecha de la Sesión')),
                ('modalidad', models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('VIRTUAL', 'Virtual')], default='PRESENCIAL', max_length=20, verbose_name='Modalidad')),
                ('resumen_general', models.TextField(verbose_name='Resumen General de la Sesión')),
                ('proxima_reunion_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Próxima Reunión Compromiso')),
                ('proxima_reunion_notas', models.TextField(blank=True, default='', verbose_name='Notas y Objetivos de la Próxima Reunión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tutoring_sessions', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_sessions', to='students.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_sessions', to='students.student')),
            ],
            options={
                'verbose_name': 'Sesión de Tutoría',
                'verbose_name_plural': 'Sesiones de Tutoría',
                'ordering': ['-fecha_sesion', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutoringObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_revisado', models.CharField(max_length=255, verbose_name='Tema o Avance Revisado')),
                ('observaciones_detalladas', models.TextField(verbose_name='Observaciones y Comentarios Académicos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_observations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='tutoring.tutoringsession')),
            ],
            options={
                'verbose_name': 'Observación de Tutoría',
                'verbose_name_plural': 'Observaciones de Tutoría',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TutoringParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_sesion', models.CharField(default='Asesor', max_length=60, verbose_name='Rol en la Sesión')),
                ('asistencia_confirmada', models.BooleanField(default=True, verbose_name='Asistencia Confirmada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutoring_participations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tutoring.tutoringsession')),
            ],
            options={
                'verbose_name': 'Participante de Tutoría',
                'verbose_name_plural': 'Participantes de Tutoría',
                'unique_together': {('session', 'user')},
            },
        ),
    ]
