# Generated by Django 6.1 on 2026-08-31 21:18

import apps.evidence.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_academiccommittee_fecha_asignacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_tipo', models.CharField(choices=[('TUTORIA', 'Sesión de Tutoría'), ('ACUERDO', 'Compromiso / Acuerdo'), ('TESIS', 'Avance de Tesis'), ('OTRO', 'Otro Producto')], default='OTRO', max_length=20, verbose_name='Tipo de Actividad Vinculada')),
                ('actividad_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de Actividad Específica')),
                ('tipo', models.CharField(choices=[('ARCHIVO_LOCAL', 'Archivo Local (PDF/Imagen/Documento)'), ('ENLACE_DOI', 'Enlace Digital / DOI Indexado')], default='ARCHIVO_LOCAL', max_length=20, verbose_name='Tipo de Evidencia')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='evidences/%Y/%m/', validators=[apps.evidence.models.validate_evidence_file], verbose_name='Archivo Adjunto')),
                ('url_doi', models.URLField(blank=True, default='', verbose_name='URL / Identificador DOI')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Tipo MIME')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño en Bytes')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción / Título del Producto')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidences', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='students.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='students.student')),
            ],
            options={
                'verbose_name': 'Evidencia Documental',
                'verbose_name_plural': 'Evidencias Documentales',
                'ordering': ['-fecha_carga'],
            },
        ),
    ]
