# Generated by Django 6.1 on 2026-08-31 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_alter_academiccommittee_fecha_asignacion'),
        ('tutoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del Compromiso / Acuerdo')),
                ('fecha_limite', models.DateField(verbose_name='Fecha Límite de Cumplimiento')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('CONCLUIDO', 'Concluido'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20, verbose_name='Estado del Acuerdo')),
                ('fecha_cambio_estado', models.DateTimeField(auto_now=True, verbose_name='Fecha de Último Cambio de Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_agreements', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_agreements', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='students.semester')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='tutoring.tutoringsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='students.student')),
            ],
            options={
                'verbose_name': 'Acuerdo de Tutoría',
                'verbose_name_plural': 'Acuerdos de Tutoría',
                'ordering': ['fecha_limite', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgreementAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(max_length=20, verbose_name='Estado Nuevo')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Cambio')),
                ('comentario', models.TextField(blank=True, default='', verbose_name='Comentario o Motivo del Cambio')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='agreements.agreement')),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_state_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de Acuerdo',
                'verbose_name_plural': 'Bitácoras de Acuerdos',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
