# Generated by Django 6.1 on 2026-08-31 21:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Matrícula Institucional')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('programa_doctoral', models.CharField(default='Doctorado en Ciencias de la Computación', max_length=255, verbose_name='Programa Doctoral')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('cohorte', models.CharField(max_length=30, verbose_name='Cohorte')),
                ('estatus_activo', models.BooleanField(default=True, verbose_name='Estatus Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2'), (3, 'Semestre 3'), (4, 'Semestre 4'), (5, 'Semestre 5'), (6, 'Semestre 6')], verbose_name='Número de Semestre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Semestre en Curso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='students.student')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['student', 'numero'],
                'unique_together': {('student', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='AcademicCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_comite', models.CharField(choices=[('ASESOR_PRINCIPAL', 'Asesor Principal'), ('COASESOR', 'Coasesor'), ('MIEMBRO_COMITE', 'Miembro del Comité')], max_length=30, verbose_name='Rol en Comité')),
                ('fecha_asignacion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Asignación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo en Comité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_assignments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_committee', to='students.student')),
            ],
            options={
                'verbose_name': 'Comité Académico',
                'verbose_name_plural': 'Comités Académicos',
                'ordering': ['student', 'rol_comite'],
                'unique_together': {('student', 'user', 'rol_comite')},
            },
        ),
    ]
