# Generated by Django 6.1 on 2026-08-31 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccommittee',
            name='fecha_asignacion',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Asignación'),
        ),
    ]
